### ISSUE TITLE
warp speed error (cuda)

### ISSUE THREAD

**Issue by rbehrouzi** [cryoem-uoft/cryosparc-issues#124]
Hi. Testing on TRPV1 example dataset, refine finished normally, but warp-speed refine gives this error message in iteration 0 with mostly empty output plots. It then goes to iteration 1 and another error message (below) and mostly empty plots. The run completes as if normal.

Error message from iteration 0 
```
Engine Started.
Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 428, in work
    ET.backproject(accumulators, force_max=force_max) # this will accumulate H, h, sigma2_est
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 285, in backproject
    stream=self.stream)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 204, in backproject
    kernels, texc = get_backproject_kernels(model_dim, have_symmetries, sym_order, False)
  File "<decorator-gen-77>", line 2, in get_backproject_kernels
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 111, in get_backproject_kernels
    SM = SourceModule(src)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
CompileError: nvcc compilation of /tmp/tmpHFmvLw/kernel.cu failed
[command: nvcc --cubin -arch sm_30 -I/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(52): error: identifier "__ldg" is undefined

kernel.cu(167): error: identifier "__ldg" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004c77_00000000-7_kernel.cpp1.ii".
]

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 428, in work
    ET.backproject(accumulators, force_max=force_max) # this will accumulate H, h, sigma2_est
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 285, in backproject
    stream=self.stream)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 204, in backproject
    kernels, texc = get_backproject_kernels(model_dim, have_symmetries, sym_order, False)
  File "<decorator-gen-77>", line 2, in get_backproject_kernels
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 111, in get_backproject_kernels
    SM = SourceModule(src)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
CompileError: nvcc compilation of /tmp/tmp2kyDXN/kernel.cu failed
[command: nvcc --cubin -arch sm_30 -I/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(52): error: identifier "__ldg" is undefined

kernel.cu(167): error: identifier "__ldg" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004c7d_00000000-7_kernel.cpp1.ii".
]

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 428, in work
    ET.backproject(accumulators, force_max=force_max) # this will accumulate H, h, sigma2_est
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 285, in backproject
    stream=self.stream)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 204, in backproject
    kernels, texc = get_backproject_kernels(model_dim, have_symmetries, sym_order, False)
  File "<decorator-gen-77>", line 2, in get_backproject_kernels
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 111, in get_backproject_kernels
    SM = SourceModule(src)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
CompileError: nvcc compilation of /tmp/tmpB3MKVS/kernel.cu failed
[command: nvcc --cubin -arch sm_30 -I/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(52): error: identifier "__ldg" is undefined

kernel.cu(167): error: identifier "__ldg" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004c89_00000000-7_kernel.cpp1.ii".
]

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 428, in work
    ET.backproject(accumulators, force_max=force_max) # this will accumulate H, h, sigma2_est
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 285, in backproject
    stream=self.stream)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 204, in backproject
    kernels, texc = get_backproject_kernels(model_dim, have_symmetries, sym_order, False)
  File "<decorator-gen-77>", line 2, in get_backproject_kernels
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_kernels.py", line 111, in get_backproject_kernels
    SM = SourceModule(src)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
CompileError: nvcc compilation of /tmp/tmpS19iqO/kernel.cu failed
[command: nvcc --cubin -arch sm_30 -I/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(52): error: identifier "__ldg" is undefined

kernel.cu(167): error: identifier "__ldg" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00004c91_00000000-7_kernel.cpp1.ii".
]
```

Message from iteration 1
```
Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 415, in work
    ET.compute_error()
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 170, in compute_error
    self.ensure_allocated('error', (self.N_D, self.N_K, self.N_RS_aligned, self.N_SS), n.float32)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 47, in ensure_allocated
    new = cuda_core.allocate_gpu(shape, dtype, curr)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 81, in allocate_gpu
    ret = gpuarray.empty(shape, dtype=dtype)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 415, in work
    ET.compute_error()
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 170, in compute_error
    self.ensure_allocated('error', (self.N_D, self.N_K, self.N_RS_aligned, self.N_SS), n.float32)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 47, in ensure_allocated
    new = cuda_core.allocate_gpu(shape, dtype, curr)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 81, in allocate_gpu
    ret = gpuarray.empty(shape, dtype=dtype)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 410, in work
    ET.load_image_data_fspace(batch)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 69, in load_image_data_fspace
    self.ensure_allocated('data_full', (self.N_D, self.N_data, self.N_data), n.complex64)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 47, in ensure_allocated
    new = cuda_core.allocate_gpu(shape, dtype, curr)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 81, in allocate_gpu
    ret = gpuarray.empty(shape, dtype=dtype)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory

Traceback (most recent call last):
  File "/home/behrouzi/cryosparc/cryosparc-compute/sparc/streamlog.py", line 254, in run_with_except_hook
    run_old(*args, **kw)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 66, in run
    self.target(*self.args, dev=self.dev, thidx=self.thidx)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 410, in work
    ET.load_image_data_fspace(batch)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 69, in load_image_data_fspace
    self.ensure_allocated('data_full', (self.N_D, self.N_data, self.N_data), n.complex64)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/engine.py", line 47, in ensure_allocated
    new = cuda_core.allocate_gpu(shape, dtype, curr)
  File "/home/behrouzi/cryosparc/cryosparc-compute/engine/cuda_core.py", line 81, in allocate_gpu
    ret = gpuarray.empty(shape, dtype=dtype)
  File "/home/behrouzi/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory
```

**Comment by alipunjani** [comment]
Hi Reza,
Which GPU are you running on? I believe this error happens if you're using a card of compute capability < 3.5.

**Comment by rbehrouzi** [comment]
Oh that's right. It's quadro k4200 which I now realize has compute capability of 3. Thanks again.
