### ISSUE TITLE
incorrect nvcc found during installation

### ISSUE THREAD

**Issue by AndyPurk** [cryoem-uoft/cryosparc-issues#132]
Installation of cryoSPARC seemed to go fine. I can load and the visualise the example data. However, when running the 'Ab-initio Heterogeneous Reconstruction' task, as suggested, I get the error at the end of this message, after the images are displayed in the browser.

Investigation shows that the installer has found the CUDA 7.5 version of nvcc, despite having both CUDA 7.5 and CUDA 8.0 installed.

Operating system is RHEL 7.3, with CUDA installed in /usr/local/cuda-7.5/ and /usr/local/cuda-8.0. Investigation of the error reported by nvcc says the the sm_61 option is only available from CUDA 8.0 onwards, despite your system requirements stating "NVIDIA Drivers and CUDA 6.5+"

Hardware is dual GeForce GTX 1080, with 132 GB RAM and dual Intel(R) Xeon(R) CPU E5-2680 v3 (12 HT cores each). I also have a new SSD installed just for testing of this package.

I would be grateful if you can provide a solution / workaround. I have attempted to set the PATH to include the CUDA 8.0 binary location, during installation, but this has failed. Also with the two versions of CUDA installed, there is a link from /usr/local/cuda-8.0 to /usr/local/cuda. Changing the PATH / LD_LIBRARY_PATH after installation doesn't work, as the installation seems to be linked to cuda-7.5 libraries.

Thanks,

Andrew Purkiss

Computing Ab-Initio Structure with volume size 64, psize 4.862.
Generating Initial Densities (seed = 1457481430)
  Generating Random Initial Density for Class 0
Traceback (most recent call last):
  File "/home/cryosparc/cryosparc-compute/sparcjob.py", line 253, in <module>
    cuda_devs = exp_params['cuda_devs'])
  File "/home/cryosparc/cryosparc-compute/abinit.py", line 217, in abinit
    premult3 = premult3)
  File "/home/cryosparc/cryosparc-compute/abinit.py", line 56, in generate_initial_density_from_projections
    ignore_dc = False)
  File "/home/cryosparc/cryosparc-compute/reconstruct.py", line 172, in reconstruction_kernel
    compute_gradient = compute_gradient)
  File "/home/cryosparc/cryosparc-compute/objectives/cudaworker.py", line 997, in set_density
    self.gHv = gpurealloc_zeros(self.gHv,self.gfMr.shape,n.float32,stream=stream)
  File "/home/cryosparc/cryosparc-compute/objectives/cudaworker.py", line 34, in gpurealloc_zeros
    ary.fill(0.0,stream=stream)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 516, in fill
    func = elementwise.get_fill_kernel(self.dtype)
  File "<decorator-gen-19>", line 2, in get_fill_kernel
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/elementwise.py", line 492, in get_fill_kernel
    "fill")
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/elementwise.py", line 161, in get_elwise_kernel
    arguments, operation, name, keep, options, **kwargs)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/elementwise.py", line 147, in get_elwise_kernel_and_types
    keep, options, **kwargs)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/elementwise.py", line 75, in get_elwise_module
    options=options, keep=keep)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/compiler.py", line 55, in preprocess_source
    cmdline, stderr=stderr)
CompileError: nvcc preprocessing of /tmp/tmpaoIHEz.cu failed
[command: nvcc --preprocess -arch sm_61 -I/home/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/cuda /tmp/tmpaoIHEz.cu --compiler-options -P]
[stderr:
nvcc fatal   : Value 'sm_61' is not defined for option 'gpu-architecture'
]

**Comment by alipunjani** [comment]
Hi Andrew, very sorry for the issue. 
Can you please try these steps:

1. Inside the cryosparc folder where the program is installed, edit the `config.sh` file and replace the cuda-7.5 paths with `/usr/local/cuda` (or `/usr/local/cuda-8.0`) for both `PATH` and `LD_LIBRARY_PATH` variables.

2. verify the paths are now correct with the following commands:
```
eval $(cryosparc env)
echo $PATH
echo $LD_LIBRARY_PATH
```

3. If cuda 8 is in the path at this point, you can do the following to re-compile PyCUDA for sm_61:
```
eval $(cryosparc env)
pip uninstall pycuda
pip install pycuda --no-cache-dir
```

After this, the cryosparc instance should work normally.

Please let us know if this works. For reference, another user had the same problem here:
https://github.com/cryoem-uoft/cryosparc-issues/issues/130

**Comment by AndyPurk** [comment]
Thanks. That seems to have worked after restarting cryosparc. 

PS Sorry for missing the previous user's issue. I only searched for open issues.

**Comment by alipunjani** [comment]
No worries :) glad it worked.
