### ISSUE TITLE
Build Issue on Linux Mint 18.1

### ISSUE THREAD

**Issue by mbelouso** [cryoem-uoft/cryosparc-issues#138]
Hey there,

When I try to install, i get the following errors when it prompts me for the output directory, then the whole installation crashes. Any thoughts on what I might be doing wrong? I'm using gcc4.9.

cheers 

  Enter path (tab-completion is enabled) 
  : /home/mbelouso/EM
  The default output directory has been set.
Traceback (most recent call last):
  File "/home/mbelouso/cryosparc/bin/configure.py", line 80, in <module>
    trycall(["cryosparc", "configure", "bulk", "add", uploadpath, 'uploads'])
  File "/home/mbelouso/cryosparc/bin/util.py", line 8, in trycall
    ret = subprocess.check_output(cmds, **kwargs)
  File "/home/mbelouso/cryosparc/anaconda2/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/mbelouso/cryosparc/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/home/mbelouso/cryosparc/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by alipunjani** [comment]
Hi @mbelouso,
Thanks for reporting - this was a silly typo I made in the new version. I've deployed a fix in version 0.3.1 so if you can try installing again it will (hopefully) now work.
Ali

**Comment by alipunjani** [comment]
@mbelouso can you confirm that installing v0.3.1 worked?

**Comment by mbelouso** [comment]
Yeah.  No dramas.  Your software is excellent.  It sorted out some data we
have been struggling with for 6 months now.  Great work mate

**Comment by alipunjani** [comment]
Awesome! Glad to hear that, thanks :)
