### ISSUE TITLE
Ab initio het recon fails to start, error in mrc.py

### ISSUE THREAD

**Issue by gfdsa146** [cryoem-uoft/cryosparc-issues#150]
Hi guys,

One of my ab initio heterogeneous reconstruction jobs failed to start.  This is the error that gets spit back at me.  Can anyone help troubleshoot?

Traceback (most recent call last):
  File "/mnt/Data_01/cryosparc/cryosparc-compute/sparcjob.py", line 188, in <module>
    dataset = dataio.dataset_factory(current_dataset_params, do_cache=current_experiment_params.get('do_cache', True))
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/__init__.py", line 18, in dataset_factory
    do_cache=do_cache)
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/load.py", line 75, in filesets_into_dataset
    load_all_referenced_mrcs(dataset, dataset, load_type, do_cache)
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/load.py", line 152, in load_all_referenced_mrcs
    mrcdata[mrcfile] = load_funcs[load_type](cachefile)
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/load.py", line 185, in load_mrc_lazy
    mrcdata = mrc.readMRClazy(fname)
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/mrc.py", line 126, in readMRClazy
    dtype = get_dtype(hdr)
  File "/mnt/Data_01/cryosparc/cryosparc-compute/dataio/mrc.py", line 120, in get_dtype
    return {1:n.int16, 2:n.float32} [hdr['datatype']]
KeyError: 1594499167

Sincerely,
Nicholas Gao

**Comment by alipunjani** [comment]
Hi Nicholas,

Thanks for reporting. It looks like one of the mrc files referenced by the dataset you created has a gibberish value in it's `datatype` header location. Usually this should be a 1 (indicating 16 bit integer) or 2 (indicating 32 bit float) but your file has a value of 1594499167.

How did you create your dataset? Is it a star file that references a single mrc, or multiple? And when you used Visualized the dataset after creating it, were there any errors?

Ali

**Comment by gfdsa146** [comment]
Doh! I figured it out.  I put the star file as the input for the Image Data File!!!

I now put the mrc as the input, and the job seems to be running.

Sincerely,
Nicholas Gao

**Comment by alipunjani** [comment]
Great! Hope things continue to work smoothly.

**Comment by Locher0107** [comment]
Yeah! I make the same mistake. My error is :+1: 

Key error: u 'mrc'.

I mistakenly put the files in wrong position.
