### ISSUE TITLE
Refinement cuMemAlloc failed

### ISSUE THREAD

**Issue by yguo01** [cryoem-uoft/cryosparc-issues#196]
Hi. I'm trying to run a refinement with one class of 13516 particles. Right after Aligning initial model to symmetry, the following message came up

Traceback (most recent call last):
  File "/home/yguo01/cryosparc/cryosparc-compute/sparcjob.py", line 332, in <module>
    superspeed = job_type=='superrefine')
  File "/home/yguo01/cryosparc/cryosparc-compute/refinement.py", line 169, in refine
    align_R,align_t = alignment.align_symmetry(initmodel,symop, cuda_dev=cuda_devs[0])
  File "/home/yguo01/cryosparc/cryosparc-compute/alignment.py", line 201, in align_symmetry
    gpuarray.to_gpu(n.copy(fV.imag).astype(n.float32)))
  File "/home/yguo01/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 975, in to_gpu
    result = GPUArray(ary.shape, ary.dtype, allocator, strides=_compact_strides(ary))
  File "/home/yguo01/cryosparc/anaconda2/lib/python2.7/site-packages/pycuda/gpuarray.py", line 209, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
MemoryError: cuMemAlloc failed: out of memory

I have run refinement for another dataset with no problem using the same parameters (box size etc.) for the same protein sample on the same workstation. Don't know what went wrong this time.

Thanks!

**Comment by alipunjani** [comment]
Hi @yguo01 sorry for the long delay in replying.
Is there any chance there was some other process using GPU memory at the time? 
Have you already been able to sort this out?

**Comment by yguo01** [comment]
Thanks for your reply! Yes, I later realized that other processes were
running. And when those completed, cryosparc refinement went just fine.

**Comment by alipunjani** [comment]
Great! Glad it's resolved.
