### ISSUE TITLE
LogicError: cuArrayCreate failed: invalid argument during 2D Classification

### ISSUE THREAD

**Issue by andreanans** [cryoem-uoft/cryosparc-issues#228]
Hi, 

I'm getting this error when trying to run 2D classification:
Our set-up is with 2 1080Ti and Cuda 8.0. Ab-initio and the rest of the functions work fine.

This happens with more than 100 classes.

Traceback (most recent call last):
  File "/home/andrean/cryosparc/cryosparc-compute/sparcjob.py", line 359, in <module>
    cuda_devs = current_experiment_params['cuda_devs'])
  File "/home/andrean/cryosparc/cryosparc-compute/class2D.py", line 270, in abinit
    num_threads_per_dev = 2)
  File "/home/andrean/cryosparc/cryosparc-compute/engine/engine.py", line 759, in process
    models_cudaarray = cuda_core.transfer_ndarray_to_cudaarray(all_models)
  File "/home/andrean/cryosparc/cryosparc-compute/engine/cuda_core.py", line 162, in transfer_ndarray_to_cudaarray
    devarr = cudrv.Array(desc)
LogicError: cuArrayCreate failed: invalid argument

**Comment by alipunjani** [comment]
I was able to reproduce the error with >300 classes on a Tesla K40 - looking into it

**Comment by alipunjani** [comment]
This is fixed, will be out in the next release. You can now use up to 4096 2D classes (until you run out of GPU RAM at least).
