### ISSUE TITLE
Webapp not working CentOS 6.7 build

### ISSUE THREAD

**Issue by drpaquet** [cryoem-uoft/cryosparc-issues#251]
am still having issues with installation on CentOS 6.7. I have gotten cryoSPARC to install but the webapp does not work. I have this error in the meteor.stdout:

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/grosslab/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/extension_binary/grpc_node.node)
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/home/grosslab/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)

Is there a work around for this yet that does not require me to pull the GLIBCXX_3.4.15 from Chrome (detailed here: [Link](https://github.com/cryoem-uoft/cryosparc-issues/issues/62) which is no longer supported on CentOS 6.7?

**Comment by spunjani** [comment]
Closing as this will be fixed in new version.
