### ISSUE TITLE
Problem submitting jobs on cluster

### ISSUE THREAD

**Issue by azazellochg** [cryoem-uoft/cryosparc-issues#286]
Hi,

the forum is down (returns 502 for me), so I thought to post my issue here. I have installed cryoSPARC 2.5.0 and connected the cluster configuration. When I submit my job to the cluster lane, I get two errors:

1) Pop-up saying Errno2 No such file or directory. If I run cryosparcm log command_core I see:
```
random_num number
Setting parameter J38.random_num with value 2 of type <type 'int'>
compute_num_gpus number
Setting parameter J38.compute_num_gpus with value 4 of type <type 'int'>
random_num number
Setting parameter J38.random_num with value 4 of type <type 'int'>
---------- Scheduler running --------------- 
Lane  lmb-gpu-nodes cluster : Jobs Queued (nonpaused, inputs ready):  [u'J38']
Now trying to schedule J38
  Need slots :  {u'GPU': 4, u'RAM': 8, u'CPU': 24}
  Need fixed :  {u'SSD': False}
  Need licen :  True
  Master direct :  False
   Trying to schedule on lmb-gpu-nodes
    Launchable:  True
    Alloc slots :  {u'GPU': [0, 1, 2, 3], u'RAM': [0, 1, 2, 3, 4, 5, 6, 7], u'CPU': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]}
    Alloc fixed :  {u'SSD': False}
    Alloc licen :  True
     -- Launchable! -- Launching.
---- Running project UID P1 job UID J38 
failed to connect link
License Data:  {"token": "a4f25901-9f27-4f34-997d-953c79424085", "token_valid": true, "request_date": 1548440385, "license_valid": true}
License Signature:  8596900413758049104149047263211697851457087196742349488795591185353876362113291116248278151471354701936513570939146984285259722485128178826759506004594028212481523129654391395594196777385877971955742735974766810257374655182222544480339321833036519416629288791815373461895233415859886961309811003519872143292281090846865558520429078239937248388928711599135541615735926645912125417933983401672469412097300461967282371879389423227518494215064926526305790077005920019213430220635208929912594954323278445448536665682435440785446885154351575757099972134790017595168004504540695132650411976503745837919612106432624997289255
     Running job on worker type cluster
unset module; qsub /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/queue_sub_script.sh
['unset', 'module;', 'qsub', '/lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/queue_sub_script.sh']
[JSONRPC ERROR  2019-01-25 18:19:45.555123  at  run_job ]
-----------------------------------------------------
Traceback (most recent call last):
  File "cryosparc2_command/command_core/__init__.py", line 106, in wrapper
    res = func(*args, **kwargs)
  File "cryosparc2_command/command_core/__init__.py", line 1522, in run_job
    res = subprocess.check_output(shlex.split(cmd), stderr=subprocess.STDOUT)
  File "/lmb/home/gsharov/soft/cryosparc/cryosparc2_master/deps/anaconda/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/lmb/home/gsharov/soft/cryosparc/cryosparc2_master/deps/anaconda/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/lmb/home/gsharov/soft/cryosparc/cryosparc2_master/deps/anaconda/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-----------------------------------------------------
[JSONRPC ERROR  2019-01-25 18:19:45.556437  at  scheduler_run ]
-----------------------------------------------------
Traceback (most recent call last):
  File "cryosparc2_command/command_core/__init__.py", line 106, in wrapper
    res = func(*args, **kwargs)
  File "cryosparc2_command/command_core/__init__.py", line 1153, in scheduler_run
    scheduler_run_core(do_run)
  File "cryosparc2_command/command_core/__init__.py", line 1290, in scheduler_run_core
    run_job(j['project_uid'], j['uid']) # takes care of the cluster case and the node case
  File "cryosparc2_command/command_core/__init__.py", line 115, in wrapper
    raise e
OSError: [Errno 2] No such file or directory
-----------------------------------------------------
[JSONRPC ERROR  2019-01-25 18:19:45.556787  at  enqueue_job ]
-----------------------------------------------------
Traceback (most recent call last):
  File "cryosparc2_command/command_core/__init__.py", line 106, in wrapper
    res = func(*args, **kwargs)
  File "cryosparc2_command/command_core/__init__.py", line 3175, in enqueue_job
    scheduler_run()
  File "cryosparc2_command/command_core/__init__.py", line 115, in wrapper
    raise e
OSError: [Errno 2] No such file or directory
-----------------------------------------------------
---------- Scheduler running --------------- 
Lane  lmb-gpu-nodes cluster : Jobs Queued (nonpaused, inputs ready):  [u'J38']
Now trying to schedule J38
  Need slots :  {u'GPU': 4, u'RAM': 8, u'CPU': 24}
  Need fixed :  {u'SSD': False}
  Need licen :  True
  Master direct :  False
   Trying to schedule on lmb-gpu-nodes
    Launchable:  True
    Alloc slots :  {u'GPU': [0, 1, 2, 3], u'RAM': [0, 1, 2, 3, 4, 5, 6, 7], u'CPU': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]}
    Alloc fixed :  {u'SSD': False}
    Alloc licen :  True
     -- Launchable! -- Launching.
Changed job P1.J38 status failed
---------- Scheduler done -----------------
```
2) In job output (web) it says:
```
Launching job on lane lmb-gpu-nodes target lmb-gpu-nodes ...

License is valid.

Launching job on cluster lmb-gpu-nodes


====================== Cluster submission script: ========================
==========================================================================
#!/bin/sh
#$ -V
#$ -N cryosparc_P1_J38
#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion
#$ -e /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/J38.err
#$ -o /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/J38.out
#$ -S /bin/bash

export CUDA_VISIBLE_DEVICES="0,1,2,3"

mpiexec -mca orte_forward_job_control 1 -n 1 /lmb/home/gsharov/soft/cryosparc/cryosparc2_worker/bin/cryosparcw run --project P1 --job J38 --master_hostname hal.lmb.internal --master_command_core_port 39002 > /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/job.log 2>&1 

==========================================================================
==========================================================================

-------- Submission command: 
unset module; qsub /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38/queue_sub_script.sh

Launching job on lane lmb-gpu-nodes target lmb-gpu-nodes ...

Job directory /lmb/home/gsharov/beegfs2/data/cryosparc-tutorial/J38 is not empty
```

Job directory is not empty indeed and contains one file - queue_sub_script.sh. What I can't figure out is what file is missing...

**Comment by azazellochg** [comment]
problem was wrong cluster_info.json commands...
