### ISSUE TITLE
cryoSPARC crashed when 

### ISSUE THREAD

**Issue by frostlab-UCSF** [cryoem-uoft/cryosparc-issues#77]
With cryoSPARC was running, we launched eman2 (e2display.py) to look at micrographs. Eman worked fine, but cryoSPARC jobs crashed.

**Comment by alipunjani** [comment]
Any error messages from cryosparc? What kind of job was running in cryosparc, and we're both cryosparc and eman2 running as the same Linux user?

**Comment by frostlab-UCSF** [comment]
cryosparc and eman2 were run as different linux users. The job was a homogenous 3D refinement. 

Error message:
	
Traceback (most recent call last):
  File "/home/cryosparc/cryosparc/cryosparc-compute/sparcjob.py", line 217, in <module>
    superspeed = job_type=='superrefine')
  File "/home/cryosparc/cryosparc/cryosparc-compute/refinement.py", line 306, in refine
    **params.search_params)
  File "/home/cryosparc/cryosparc/cryosparc-compute/search.py", line 359, in heuristicsearches
    doscale = doscale, ignore_dc = ignore_dc, cuda_workers = cuda_workers)
  File "/home/cryosparc/cryosparc/cryosparc-compute/search.py", line 241, in compute_Us
    results = pool.map(work, zip(images, rss, tss))
  File "/home/cryosparc/cryosparc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/cryosparc/cryosparc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
LogicError: cuStreamSynchronize failed: an illegal memory access was encountered

**Comment by alipunjani** [comment]
Hmm... I believe this is related to a bug that we're fixing in the GPU kernels in cryosparc. If it only happened once when you launched eman2, I think it may have been a coincidence (since cryosparc on your machine has had this same cuStreamSync error before, and I don't think there should be any clash between eman2 and cryosparc). Sorry it keeps happening! 
I think for now the only solution is to re-run the cryosparc job. This bug will definitely get fixed in the new GPU kernels. 

Thanks a lot for helping us debug and sorry for the annoyance of crashed jobs!
Ali

**Comment by mbrubake** [comment]
Closing for now, particularly with the new CUDA kernels coming soon.  We can reopen if this pops up again
