### ISSUE TITLE
Phase Plate Data

### ISSUE THREAD

**Issue by tanyongzi** [cryoem-uoft/cryosparc-issues#89]
I finally got around to testing the phase plate dataset on the latest CryoSPARC. However it seems to throw up an error during ab initio:

Traceback (most recent call last):
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/sparcjob.py", line 218, in <module>
    cuda_devs = exp_params['cuda_devs'])
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/abinit.py", line 338, in abinit
    class_anneal_beta = class_anneal_beta)
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/reconstruct.py", line 281, in reconstruction_kernel
    work(img)
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/reconstruct.py", line 229, in work
    IW.compute_conditional_normalization_constant_and_logphis()
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/objectives/cudaworker.py", line 1462, in compute_conditional_normalization_constant_and_logphis
    assert n.isfinite(self.conditional_logZ)
AssertionError

Could it be a problem with the amplitude contrast? Thank you.

**Comment by mbrubake** [comment]
Hmmmm, @tanyongzi could you provide a bit more info on this?  When does this error occur?  At the very beginning?  After a few iterations?  I have a hunch but it depends on when it is occuring.

**Comment by tanyongzi** [comment]
It occurs right at the start. When I now try to do a refinement, I get a different error, but also at the start:

Traceback (most recent call last):
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/sparcjob.py", line 229, in <module>
    superspeed = job_type=='superrefine')
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/refinement.py", line 306, in refine
    **params.search_params)
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/search.py", line 359, in heuristicsearches
    doscale = doscale, ignore_dc = ignore_dc, cuda_workers = cuda_workers)
  File "/mnt/fast_scratch/progs/cryosparc/cryosparc-compute/search.py", line 241, in compute_Us
    results = pool.map(work, zip(images, rss, tss))
  File "/mnt/fast_scratch/progs/cryosparc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/mnt/fast_scratch/progs/cryosparc/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ZeroDivisionError: float division by zero

Maybe it would be a good idea to integrate phase plate information as a separate flag (like Relion 2), instead of hacking it in with the amplitude contrast, for a longer term solution.

**Comment by mbrubake** [comment]
Yes, improving the CTF model is definitely the right solution (see #92) but assuming the values for the amplitude contrasts are set right, it should have exactly the same effect which means something else may be going wrong here.

**Comment by alipunjani** [comment]
Hi Yong Zi,
Sorry for this trouble. As @mbrubake said definitely a modified CTF model is the right way. I haven't had a chance to test the dataset you uploaded yet, but we'll figure this out.

**Comment by alipunjani** [comment]
Hey @tanyongzi good news: @mbrubake implemented the phase plate CTF (using rlnPhaseShift from star file input) now I've tested it, it now works in v0.2.36!

I tested on the dataset you sent us, it worked well. I'll send you an email with the results.
